services:
  neuraforge-docs:
    container_name: neuraforge-docs
    build:
      context: .
      dockerfile: Dockerfile
    image: neuraforge-docs:latest
    restart: unless-stopped
    expose:
      - "80"
    networks:
      reverse-proxy:
        aliases:
          - neuraforge-docs

networks:
  reverse-proxy:
    external: true
    name: reverse-proxy
